#!/bin/bash

[[ -z "$DEBUG" ]] || set -x # Enable debugging
set -e # exit on error to be safe

if [[ -z "$RU_STAGEDIR" && -d _stage ]]
then
  export RU_STAGEDIR="_stage"
else
  echo "     Did you run recover-machine-00-set-stage?"
  exit 1
fi

if [[ -r $RU_STAGEDIR/00-FUNCTIONS && \
        -r $RU_STAGEDIR/00-LOCALENV  ]]
then
  source $RU_STAGEDIR/00-FUNCTIONS 
  source $RU_STAGEDIR/00-LOCALENV 
else
  echo "     Can't find all my files:"
  ls -l $RU_STAGEDIR/00-FUNCTIONS
  ls -l $RU_STAGEDIR/00-LOCALENV
  exit 1
fi

echo "     Archive active unit directories (expect and ignore 'socket ignored' warnings)"
juju ssh "$RU_ACTIVE_UNIT" sudo tar -C /var/lib -c${V}f /tmp/RU_var_lib.tar \
                                             ./juju/agents/$RU_ACTIVE_UNIT_FILENAME \
                                             ./juju/tools/$RU_ACTIVE_UNIT_FILENAME
juju ssh "$RU_ACTIVE_UNIT" sudo tar -C /etc/systemd/system -c${V}f /tmp/RU_etc_systemd_system.tar \
                                            ./jujud-${RU_ACTIVE_UNIT_FILENAME}-exec-start.sh \
                                            ./jujud-${RU_ACTIVE_UNIT_FILENAME}.service
juju ssh "$RU_ACTIVE_UNIT" sudo chmod 644 /tmp/RU_var_lib.tar /tmp/RU_etc_systemd_system.tar
juju ssh "$RU_ACTIVE_UNIT" ls -l /tmp/RU_*.tar

echo "     Retrieve active unit directory archives"
juju scp "$RU_ACTIVE_UNIT":/tmp/RU_var_lib.tar            $RU_STAGEDIR/01_SRC_var_lib.tar
juju scp "$RU_ACTIVE_UNIT":/tmp/RU_etc_systemd_system.tar $RU_STAGEDIR/01_SRC_etc_systemd_system.tar
ls -l $RU_STAGEDIR/01_SRC_*.tar

recover_mkdir $RU_STAGEDIR/01_SRC_var_lib
recover_mkdir $RU_STAGEDIR/01_SRC_etc_systemd_system

echo "     Extract active unit directories from archives"
sudo tar -C      $RU_STAGEDIR/01_SRC_var_lib            -x${V}f $RU_STAGEDIR/01_SRC_var_lib.tar
sudo tar -C      $RU_STAGEDIR/01_SRC_etc_systemd_system -x${V}f $RU_STAGEDIR/01_SRC_etc_systemd_system.tar
echo "$RU_STAGEDIR/01_SRC_var_lib:"
ls -l $RU_STAGEDIR/01_SRC_var_lib
echo "$RU_STAGEDIR/01_SRC_etc_systemd_system:"
ls -l $RU_STAGEDIR/01_SRC_etc_systemd_system
