#!/usr/bin/bash

if [[ ! -r recover-unit-00-LOCALENV ]]
then
  echo "    Create recover-unit-00-LOCALENV file (see recover-unit-00-LOCALENV.sample)"
  exit
else
  source recover-unit-00-LOCALENV
fi

if [[ ! -d $STAGEDIR/03_tgt_var_lib_juju_agents_${SRCUNIT_DASH}      || \
      ! -d $STAGEDIR/03_tgt_etc_systemd_system_jujud-${SRCUNIT_DASH} ]]
then
  echo "    Have you run recover-unit-03-edit-staged-tgt-target-directories?"
  echo "    Can't find target directories in $STAGEDIR"
  ls -l $STAGEDIR
  exit 1
fi

echo "    Archive directories"
tar -C $STAGEDIR/tgt_var_lib_juju_agents_${TGTUNIT_DASH}      -c${V}f $STAGEDIR/tgt_var_lib_juju_agents_${SRCUNIT_DASH}.tar      .
tar -C $STAGEDIR/tgt_etc_systemd_system_jujud_${TGTUNIT_DASH} -c${V}f $STAGEDIR/tgt_etc_systemd_system_jujud_${SRCUNIT_DASH}.tar . 
ls -l $STAGEDIR/tgt_*.tar
