#!/usr/bin/bash

if [[ ! -r recover-machine-00-LOCALENV ]]
then
  echo "    Create recover-machine-00-LOCALENV file (see recover-machine-00-LOCALENV.sample)"
  exit
else
  source recover-machine-00-LOCALENV
fi

if [[ ! -d $STAGEDIR/03_TGT_var_lib_juju_agents_${SRCMACHINE_DASH}      || \
      ! -d $STAGEDIR/03_TGT_etc_systemd_system_jujud-${SRCMACHINE_DASH} ]]
then
  echo "    Have you run recover-machine-03-edit-staged-tgt-target-directories?"
  echo "    Can't find target directories in $STAGEDIR"
  ls -l $STAGEDIR
  exit 1
fi

echo "    Archive directories"
tar -C $STAGEDIR/tgt_var_lib_juju_agents_${TGTMACHINE_DASH}      -c${V}f $STAGEDIR/tgt_var_lib_juju_agents_${SRCMACHINE_DASH}.tar      .
tar -C $STAGEDIR/tgt_etc_systemd_system_jujud_${TGTMACHINE_DASH} -c${V}f $STAGEDIR/tgt_etc_systemd_system_jujud_${SRCMACHINE_DASH}.tar . 
ls -l $STAGEDIR/tgt_*.tar
