#!/usr/bin/bash

if [[ -z "$RECOVERY_STAGEDIR" ]]
then
  export RECOVERY_STAGEDIR="./_stage"
fi

# Define functions here:
function recover_mkdir
{
  local dir=$1

  if [ -d $dir ]
  then
    timestamp=$(stat --format %y $dir | tr ' :' '_-')
    echo -e "\n    Move old staged target directory $dir out of the way to $dir.${timestamp}"
    sudo mv $dir $dir.${timestamp}
    ls -ld $dir.${timestamp}
  fi
  echo -e "\n    Make target directory"
  mkdir -p $dir
  ls -ld $dir
}
recover_mkdir $RECOVERY_STAGEDIR
# Dump functions in file to be sourced by other scripts:
echo -e "\n    Create function file"
declare -f recover_mkdir > $RECOVERY_STAGEDIR/00-FUNCTIONS
ls -l $RECOVERY_STAGEDIR/00-FUNCTIONS

echo -e "\n    Get juju status"
juju status --format json > $RECOVERY_STAGEDIR/00-status.json
ls -l $RECOVERY_STAGEDIR/00-status.json

echo -e "\n    Determine application that is stuck installing"
RECOVERY_APPLICATION=$(cat $RECOVERY_STAGEDIR/00-status.json \
             | jq -r '.applications[]
                     | select(."application-status".message == "installing agent")."charm-name"
                     ' \
             )
echo $RECOVERY_APPLICATION

echo -e "\n    Determine target machine with application installing agent"
RECOVERY_TGT_MACHINENUM=$(cat $RECOVERY_STAGEDIR/00-status.json \
               | jq -r '.applications[]?.units[]?
                       | select(.subordinates != null)
                       | select(.subordinates[]."workload-status".message == "installing agent").machine
                       ' \
               )
echo $RECOVERY_TGT_MACHINENUM

echo -e "\n    Determine source machine with application active"
RECOVERY_SRC_MACHINENUM=$(cat $RECOVERY_STAGEDIR/00-status.json \
               | jq -r '.applications[]?.units[]?
                       | select(.subordinates != null)
                       | select(.subordinates[]."workload-status".current == "active").machine
                       ' \
               | tail -1
               )
echo $RECOVERY_SRC_MACHINENUM

RECOVERY_TGT_MACHINE=machine-$RECOVERY_TGT_MACHINENUM
RECOVERY_SRC_MACHINE=machine-$RECOVERY_SRC_MACHINENUM

echo -e "\n    Populate local environment file"
cat <<END > $RECOVERY_STAGEDIR/00-LOCALENV
export RECOVERY_STAGEDIR=$RECOVERY_STAGEDIR
export RECOVERY_APPLICATION=$RECOVERY_APPLICATION
export RECOVERY_TGT_MACHINENUM=$RECOVERY_TGT_MACHINENUM
export RECOVERY_SRC_MACHINENUM=$RECOVERY_SRC_MACHINENUM
export RECOVERY_TGT_MACHINE=$RECOVERY_TGT_MACHINE
export RECOVERY_SRC_MACHINE=$RECOVERY_SRC_MACHINE
END
cat $RECOVERY_STAGEDIR/00-LOCALENV
