#!/usr/bin/bash

if [[ ! -r "recover-machine-00-LOCALENV" ]]
then
  echo "    Create recover-machine-00-LOCALENV file (see recover-machine-00-LOCALENV.sample)"
  exit
else
  source recover-machine-00-LOCALENV
fi

if [[ ! -d "$STAGEDIR" ]]
then
  echo "    Did you run recvover-machine-01-prepare-stage?"
  exit 1
fi

echo "    Archive source directories on source machine"
juju ssh "$SRCMACHINE_SLASH" cat /etc/hostname
juju ssh "$SRCMACHINE_SLASH" sudo tar -C /var/lib/juju/agents/$SRCMACHINE_DASH -c${V}f /tmp/src_var_lib_juju_agents_${SRCMACHINE_DASH}.tar      ./
juju ssh "$SRCMACHINE_SLASH" sudo tar -C /etc/systemd/system                -c${V}f /tmp/src_etc_systemd_system_jujud-${SRCMACHINE_DASH}.tar ./jujud-${SRCMACHINE_DASH}-exec-start.sh ./jujud-${SRCMACHINE_DASH}.service
juju ssh "$SRCMACHINE_SLASH" ls -l /tmp/src_*.tar
echo "    Retrieve source directory archives"
juju scp "$SRCMACHINE_SLASH":/tmp/src_var_lib_juju_agents_${SRCMACHINE_DASH}.tar      $STAGEDIR/02_src_var_lib_juju_agents_${SRCMACHINE_DASH}.tar
juju scp "$SRCMACHINE_SLASH":/tmp/src_etc_systemd_system_jujud-${SRCMACHINE_DASH}.tar $STAGEDIR/02_src_etc_systemd_system_jujud-${SRCMACHINE_DASH}.tar
ls -l $STAGEDIR/02_src_*.tar
