#!/bin/bash

[[ -z "$DEBUG" ]] || set -x # Enable debugging
set -e # exit on error to be safe
scriptname=$(basename $0)

if echo '{}' | jq . > /dev/null 2>&1
then
  :
else
  echo "Please install prerequisite tool jq"
  exit 1
fi

if [ "$#" -ne 1 ]; then
  cat <<-USAGE 1>&2
	Usage: $scriptname model controller_model
	       where model is the model name to check
	
	       You can control the staging directory location:
	         export RU_STAGEDIR=_stage
	
	       You can enable debugging:
	         export DEBUG=1
	         $scriptname modelname
	       or:
	         DEBUG=1 $scriptname modelname
	USAGE
  exit 0
else
  echo "     Get model name"
  RU_MODEL_NAME=$1
  RU_CTRL_MODEL_NAME=$2
  echo "===> Got $RU_MODEL_NAME"
fi
echo "     Switch Juju to $RU_MDOEL_NAME"
juju switch $RU_MODEL_NAME

if [[ -z "$RU_STAGEDIR" ]]
then
  export RU_STAGEDIR="_stage"
fi

# Define functions here:
function recover_mkdir
{
  local dir=$1

  if [ -d $dir ]
  then
    timestamp=$(stat --format %y $dir | tr ' :' '_-')
    echo "     Move old staged target directory $dir out of the way to $dir.${timestamp}"
    sudo mv $dir $dir.${timestamp}
    ls -ld $dir.${timestamp}
  fi
  echo "     Make target directory"
  mkdir -p $dir
  ls -ld $dir
}
recover_mkdir $RU_STAGEDIR
# Dump functions in file to be sourced by other scripts:
echo "     Create function file"
declare -f recover_mkdir > $RU_STAGEDIR/00-FUNCTIONS
ls -l $RU_STAGEDIR/00-FUNCTIONS

echo "     Get juju status and store it in $RU_STAGEDIR/00-status.json"
juju status --format json > $RU_STAGEDIR/00-status.json
ls -l $RU_STAGEDIR/00-status.json

echo "     Get application that is stuck installing from $RU_STAGEDIR/00-status.json"
RU_APPLICATION=$(cat $RU_STAGEDIR/00-status.json \
             | jq -r '.applications[]
                     | select(."application-status".message == "installing agent")."charm-name"
                     ' \
             )
echo "===> Got $RU_APPLICATION"

echo "     Get unit that is stuck installing from $RU_STAGEDIR/00-status.json"
RU_INSTALLING_UNIT=$(cat $RU_STAGEDIR/00-status.json \
             | jq -r '.applications[]?.units[]? 
                      | select(.subordinates != null) 
                      | .subordinates 
                      | {unit: keys[], message: .[]."workload-status".message}
                      | select(.message=="installing agent") | .unit
                     ' \
             )
echo "===> Got $RU_INSTALLING_UNIT"

echo "     Get unit that is from $RU_STAGEDIR/00-status.json"
RU_ACTIVE_UNIT=$(cat $RU_STAGEDIR/00-status.json \
             | jq -r '.applications[]?.units[]? 
                      | select(.subordinates != null) 
                      | .subordinates 
                      | {unit: keys[], current: .[]."workload-status".current}
                      | select(.current=="active") | .unit
                     ' \
             | tail -1 \
             )
echo "===> Got $RU_ACTIVE_UNIT"

RU_ACTIVE_UNIT_FILENAME=unit-$(echo $RU_ACTIVE_UNIT | tr / -)
RU_INSTALLING_UNIT_FILENAME=unit-$(echo $RU_INSTALLING_UNIT | tr / -)

echo "     Get first started controller num"
RU_CTRLR_NUM=$(juju machines -m ${RU_CTRL_MODEL_NAME} | awk '/started/{print $1}' | head -n1) # grab first started controller _NUM
echo "===> Got $RU_CTRLR_NUM"

echo "     Get first controller mongo password"
RU_MONGO_PW=$(juju ssh -m ${RU_CTRL_MODEL_NAME} ubuntu@$RU_CTRLR_NUM "sudo awk '/^apipassword:/ {print \$2}' /var/lib/juju/agents/machine*/agent.conf" | tr -d '\r')
echo "===> Got $RU_MONGO_PW"

echo "     Get first controller mongo client executable using executable name mongo"
RU_MONGO_EXEC=$(juju ssh -m ${RU_CTRL_MODEL_NAME} ubuntu@$RU_CTRLR_NUM which mongo | tr -d '\r')
if [[ -z "$RU_MONGO_EXEC" ]]
then
  echo "===> Mongo client executable not found with name 'mongo'"
  echo "     Get first controller mongo client executable using executable name juju-db.mongo"
  RU_MONGO_EXEC=$(juju ssh -m ${RU_CTRL_MODEL_NAME} ubuntu@$RU_CTRLR_NUM which juju-db.mongo | tr -d '\r')
  if [[ -z "$RU_MONGO_EXEC" ]]
  then
    echo "Failed to find mongo client executable."
    exit 2
  fi
fi
echo "===> Got $RU_MONGO_EXEC"

echo "     Upload RU_STAGEDIR/00-MONGO_RUN-CODE to first controller to facilitate mongo db queries."
cat <<END > $RU_STAGEDIR/00-MONGO_RUN-CODE
$RU_MONGO_EXEC -port 37017 --sslAllowInvalidCertificates --ssl --authenticationDatabase admin -u machine-$RU_CTRLR_NUM -p $RU_MONGO_PW juju </tmp/00-MONGO_CODE 2>/dev/null
END
juju scp -m ${RU_CTRL_MODEL_NAME} $RU_STAGEDIR/00-MONGO_RUN-CODE "$RU_CTRLR_NUM":/tmp/

echo "     Get primary controller IP from first controller mongo db"
cat <<END > $RU_STAGEDIR/00-MONGO_CODE
use juju
rs.isMaster()['primary']
END
juju scp -m ${RU_CTRL_MODEL_NAME} $RU_STAGEDIR/00-MONGO_CODE "$RU_CTRLR_NUM":/tmp/
RU_CTRLR_IP=$(juju ssh -m ${RU_CTRL_MODEL_NAME} ubuntu@$RU_CTRLR_NUM sudo bash /tmp/00-MONGO_RUN-CODE | tail -n 2 | head -n 1 | awk -F: '{print $1}')
echo "===> Got $RU_CTRLR_IP"

echo "     Get primary controller num"
RU_CTRLR_NUM=$(juju machines -m ${RU_CTRL_MODEL_NAME} | awk -v ip=$RU_CTRLR_IP '$0 ~ ip {print $1}' | head -n1) # grab primary controller NUM using IP
echo "===> Got $RU_CTRLR_NUM"

echo "     Get primary controller mongo password"
RU_MONGO_PW=$(juju ssh -m ${RU_CTRL_MODEL_NAME} ubuntu@$RU_CTRLR_NUM "sudo awk '/^apipassword:/ {print \$2}' /var/lib/juju/agents/machine-${RU_CTRLR_NUM}/agent.conf" | tr -d '\r')
echo "===> Got $RU_MONGO_PW"

echo "     Get primary controller mongo client executable using executable name mongo"
RU_MONGO_EXEC=$(juju ssh -m ${RU_CTRL_MODEL_NAME} ubuntu@$RU_CTRLR_NUM which mongo | tr -d '\r')
if [[ -z "$RU_MONGO_EXEC" ]]
then
  echo "===> Mongo client executable not found with name 'mongo'"
  echo "     Get first controller mongo client executable using executable name juju-db.mongo"
  RU_MONGO_EXEC=$(juju ssh -m ${RU_CTRL_MODEL_NAME} ubuntu@$RU_CTRLR_NUM which juju-db.mongo | tr -d '\r')
  if [[ -z "$RU_MONGO_EXEC" ]]
  then
    echo "Failed to find mongo client executable."
    exit 2
  fi
fi
echo "===> Got $RU_MONGO_EXEC"

echo "     Upload $RU_STAGEDIR/00-MONGO_RUN-CODE to primary controller to facilitate mongo db queries."
cat <<END > $RU_STAGEDIR/00-MONGO_RUN-CODE
$RU_MONGO_EXEC -port 37017 --sslAllowInvalidCertificates --ssl --authenticationDatabase admin -u machine-$RU_CTRLR_NUM -p $RU_MONGO_PW juju </tmp/00-MONGO_CODE 2>/dev/null
END
juju scp -m ${RU_CTRL_MODEL_NAME} $RU_STAGEDIR/00-MONGO_RUN-CODE "$RU_CTRLR_NUM":/tmp/

echo "     Get model uuid from primary controller mongo db"
cat <<END > $RU_STAGEDIR/00-MONGO_CODE
use juju
db.models.find({"name": "$RU_MODEL_NAME"}, {"modeluuid": 1})
END
juju scp -m ${RU_CTRL_MODEL_NAME} $RU_STAGEDIR/00-MONGO_CODE "$RU_CTRLR_NUM":/tmp/
RU_MODEL_UUID=$(juju ssh -m ${RU_CTRL_MODEL_NAME} ubuntu@$RU_CTRLR_NUM sudo bash /tmp/00-MONGO_RUN-CODE | tr -d '\r' | egrep '^{' | jq -r ._id)
echo "===> Got $RU_MODEL_UUID"

echo "     Get active unit password hash from primary controller mongo db"
cat <<END > $RU_STAGEDIR/00-MONGO_CODE
use juju
db.units.find({"_id": "${RU_MODEL_UUID}:${RU_ACTIVE_UNIT}"}, {"passwordhash":1})
END
juju scp -m ${RU_CTRL_MODEL_NAME} $RU_STAGEDIR/00-MONGO_CODE "$RU_CTRLR_NUM":/tmp/
RU_ACTIVE_UNIT_PWHASH=$(juju ssh -m ${RU_CTRL_MODEL_NAME} ubuntu@$RU_CTRLR_NUM sudo bash /tmp/00-MONGO_RUN-CODE | tr -d '\r' | egrep '^{' | jq -r .passwordhash)
echo "===> Got $RU_ACTIVE_UNIT_PWHASH"

echo "     Get installing unit password hash from primary controller mongo db"
cat <<END > $RU_STAGEDIR/00-MONGO_CODE
use juju
db.units.find({"_id": "${RU_MODEL_UUID}:${RU_INSTALLING_UNIT}"}, {"passwordhash":1})
END
juju scp -m ${RU_CTRL_MODEL_NAME} $RU_STAGEDIR/00-MONGO_CODE "$RU_CTRLR_NUM":/tmp/
RU_INSTALLING_UNIT_PWHASH=$(juju ssh -m ${RU_CTRL_MODEL_NAME} ubuntu@$RU_CTRLR_NUM sudo bash /tmp/00-MONGO_RUN-CODE | tr -d '\r' | egrep '^{' | jq -r .passwordhash)
echo "===> Got $RU_INSTALLING_UNIT_PWHASH"

echo "     Get livepatch_key from juju config for canonical-livepatch"
########## WARNING HARDCODED to canonical-livepatch ##########
RU_APPLICATION_KEY=$(juju config $RU_APPLICATION --format json | jq -r '.settings.livepatch_key.value')
echo "===> Got $RU_APPLICATION_KEY"

echo "     Populate local environment file"
for keyval in $(declare | grep ^RU_ | sort)
do
  echo export $keyval
done | tee $RU_STAGEDIR/00-LOCALENV
