#!/bin/bash

[[ -z "$DEBUG" ]] || set -x # Enable debugging
set -e # exit on error to be safe

if [[ -z "$RU_STAGEDIR" && -d _stage ]]
then
  export RU_STAGEDIR="_stage"
else
  echo "     Did you run recover-machine-00-set-stage?"
  exit 1
fi

if [[ -r $RU_STAGEDIR/00-FUNCTIONS && \
        -r $RU_STAGEDIR/00-LOCALENV  ]]
then
  source $RU_STAGEDIR/00-FUNCTIONS
  source $RU_STAGEDIR/00-LOCALENV
  env | grep RU_ | sort
else
  echo "     Can't find all my files:"
  ls -l $RU_STAGEDIR/00-FUNCTIONS
  ls -l $RU_STAGEDIR/00-LOCALENV
  exit 1
fi

if [[ ! -r "$RU_STAGEDIR/01_SRC_var_lib.tar" ||   \
      ! -r "$RU_STAGEDIR/01_SRC_etc_systemd_system.tar" ]]
then
  echo "     Have you run recover-machine-01-get-src-directories?"
  echo "     Can't find source archives in $RU_STAGEDIR"
  ls -l $RU_STAGEDIR/01_SRC_var_lib.tar
  ls -l $RU_STAGEDIR/01_SRC_etc_systemd_system.tar
  exit 1
else
  source $RU_STAGEDIR/00-FUNCTIONS
  source $RU_STAGEDIR/00-LOCALENV
fi

recover_mkdir $RU_STAGEDIR/03_TGT_NEW_var_lib
recover_mkdir $RU_STAGEDIR/03_TGT_NEW_etc_systemd_system

echo "     Extract source directory archives into new target directories"
sudo tar -C $RU_STAGEDIR/03_TGT_NEW_var_lib            -x${V}f $RU_STAGEDIR/01_SRC_var_lib.tar
sudo tar -C $RU_STAGEDIR/03_TGT_NEW_etc_systemd_system -x${V}f $RU_STAGEDIR/01_SRC_etc_systemd_system.tar
echo $RU_STAGEDIR/03_TGT_NEW_var_lib:
ls -l  $RU_STAGEDIR/03_TGT_NEW_var_lib
echo $RU_STAGEDIR/03_TGT_NEW_etc_systemd_system:
ls -l  $RU_STAGEDIR/03_TGT_NEW_etc_systemd_system

echo "     Edit new target files"
sudo mv -f  $RU_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RU_ACTIVE_UNIT_FILENAME} $RU_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RU_INSTALLING_UNIT_FILENAME}
sudo mv -f  $RU_STAGEDIR/03_TGT_NEW_var_lib/juju/tools/${RU_ACTIVE_UNIT_FILENAME}  $RU_STAGEDIR/03_TGT_NEW_var_lib/juju/tools/${RU_INSTALLING_UNIT_FILENAME}
sudo sed -i "s/${RU_ACTIVE_UNIT_FILENAME}/${RU_INSTALLING_UNIT_FILENAME}/g" $RU_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RU_INSTALLING_UNIT_FILENAME}/agent.conf
sudo sed -i "s/${RU_ACTIVE_UNIT_FILENAME}/${RU_INSTALLING_UNIT_FILENAME}/g" $RU_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RU_INSTALLING_UNIT_FILENAME}/.venv/bin/activate*
sudo mv -f  $RU_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RU_ACTIVE_UNIT_FILENAME}-exec-start.sh $RU_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RU_INSTALLING_UNIT_FILENAME}-exec-start.sh
sudo mv -f  $RU_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RU_ACTIVE_UNIT_FILENAME}.service       $RU_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RU_INSTALLING_UNIT_FILENAME}.service
sudo sed -i "s/${RU_ACTIVE_UNIT_FILENAME}/${RU_INSTALLING_UNIT_FILENAME}/g" $RU_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RU_INSTALLING_UNIT_FILENAME}*

echo "     Diff of directories"
set +e # Temporarily don't exit on error because we expect diff to find differences
for i in $RU_STAGEDIR/01_SRC_var_lib/juju/agents/${RU_ACTIVE_UNIT_FILENAME}/agent.conf           \
         $RU_STAGEDIR/01_SRC_var_lib/juju/agents/${RU_ACTIVE_UNIT_FILENAME}/.venv/bin/activate* \
         $RU_STAGEDIR/01_SRC_etc_systemd_system/jujud-${RU_ACTIVE_UNIT_FILENAME}-exec-start.sh   \
         $RU_STAGEDIR/01_SRC_etc_systemd_system/jujud-${RU_ACTIVE_UNIT_FILENAME}.service
do
  j=$(echo $i | sed -e "s/01_SRC/03_TGT_NEW/; s/${RU_ACTIVE_UNIT_FILENAME}/${RU_INSTALLING_UNIT_FILENAME}/")
  sudo diff --recursive --unified --no-dereference $i $j
done > $RU_STAGEDIR/03-diffs.log 2>&1
echo "===> Diffs are in $RU_STAGEDIR/03-diffs.log"

echo "#### Review diffs using, for example:"
echo "vim $RU_STAGEDIR/03-diffs.log"
echo "#### If any further edits or changes are needed, either add to this script and rerun or"
echo "#### manually edit/change $RU_STAGEDIR/03_TGT_NEW_* files as needed and proceed with next step."
