#!/usr/bin/bash

[[ -z "$DEBUG" ]] || set -x # Enable debugging
set -e # exit on error to be safe

if [[ -z "$RU_STAGEDIR" && -d _stage ]]
then
  export RU_STAGEDIR="_stage"
else
  echo "     Did you run recover-machine-00-set-stage?"
  exit 1
fi

if [[ -r $RU_STAGEDIR/00-FUNCTIONS && \
        -r $RU_STAGEDIR/00-LOCALENV  ]]
then
  source $RU_STAGEDIR/00-FUNCTIONS
  source $RU_STAGEDIR/00-LOCALENV
else
  echo "     Can't find all my files:"
  ls -l $RU_STAGEDIR/00-FUNCTIONS
  ls -l $RU_STAGEDIR/00-LOCALENV
  exit 1
fi

echo "     Archive target directories on target machine (expect and ignore 'socket ignored' warnings)"
set +e # These are expected to error but we try anyway
juju ssh "$RU_INSTALLING_UNIT" sudo tar -C /var/lib -c${V}f /tmp/RU_var_lib.tar \
                                                ./juju/agents/${RU_INSTALLING_UNIT_FILENAME} \
                                                ./juju/tools/${RU_INSTALLING_UNIT_FILENAME}
juju ssh "$RU_INSTALLING_UNIT" sudo tar -C /etc/systemd/system -c${V}f /tmp/RU_etc_systemd_system.tar \
                                                ./jujud-${RU_INSTALLING_UNIT_FILENAME}-exec-start.sh \
                                                ./jujud-${RU_INSTALLING_UNIT_FILENAME}.service
juju ssh "$RU_INSTALLING_UNIT" ls -l /tmp/RU_*.tar
set -e

echo "     Retrieve target directory archives from target machine"
juju scp "$RU_INSTALLING_UNIT":/tmp/RU_var_lib.tar            $RU_STAGEDIR/02_TGT_BKP_var_lib.tar
juju scp "$RU_INSTALLING_UNIT":/tmp/RU_etc_systemd_system.tar $RU_STAGEDIR/02_TGT_BKP_etc_systemd_system.tar
ls -l $RU_STAGEDIR/02_TGT_BKP_*.tar

if [ -d $RU_STAGEDIR/02_TGT_BKP_var_lib ]
then
  timestamp=$(stat --format %y $RU_STAGEDIR/02_TGT_BKP_var_lib | tr ' :' '_-')
  echo "     Move old staged target backup directory $RU_STAGEDIR/02_TGT_BKP_var_lib out of the way to ${RU_STAGEDIR}/02_TGT_BKP_var_lib.${timestamp}"
  sudo mv $RU_STAGEDIR/02_TGT_BKP_var_lib  ${RU_STAGEDIR}/02_TGT_BKP_var_lib.${timestamp}
  ls -ld ${RU_STAGEDIR}/02_TGT_BKP_var_lib.${timestamp}
fi

if [ -d $RU_STAGEDIR/02_TGT_BKP_etc_systemd_system ]
then
  timestamp=$(stat --format %y $RU_STAGEDIR/02_TGT_BKP_etc_systemd_system | tr ' :' '_-')
  echo "     Move old staged backup target directory $RU_STAGEDIR/02_TGT_BKP_etc_systemd_system out of the way to ${RU_STAGEDIR}/02_TGT_BKP_etc_systemd_system.${timestamp}"
  sudo mv $RU_STAGEDIR/02_TGT_BKP_etc_systemd_system $RU_STAGEDIR/02_TGT_BKP_etc_systemd_system.${timestamp}
  ls -ld  $RU_STAGEDIR/02_TGT_BKP_etc_systemd_system.${timestamp}
fi

recover_mkdir $RU_STAGEDIR/02_TGT_BKP_var_lib
recover_mkdir $RU_STAGEDIR/02_TGT_BKP_etc_systemd_system

echo "     Extract target directories from archives"
sudo tar -C      $RU_STAGEDIR/02_TGT_BKP_var_lib            -x${V}f $RU_STAGEDIR/02_TGT_BKP_var_lib.tar
sudo tar -C      $RU_STAGEDIR/02_TGT_BKP_etc_systemd_system -x${V}f $RU_STAGEDIR/02_TGT_BKP_etc_systemd_system.tar
echo "$RU_STAGEDIR/02_TGT_BKP_var_lib:"
ls -l $RU_STAGEDIR/02_TGT_BKP_var_lib
echo "$RU_STAGEDIR/02_TGT_BKP_etc_systemd_system:"
ls -l $RU_STAGEDIR/02_TGT_BKP_etc_systemd_system
