#!/usr/bin/bash

[[ -z "$DEBUG" ]] || set -x # Enable debugging
set -e # exit on error to be safe

if [[ -z "$RM_STAGEDIR" && -d _stage ]]
then
  export RM_STAGEDIR="_stage"
else
  echo "     Did you run recover-machine-00-set-stage?"
  exit 1
fi

if [[ -r $RM_STAGEDIR/00-FUNCTIONS && \
        -r $RM_STAGEDIR/00-LOCALENV  ]]
then
  source $RM_STAGEDIR/00-FUNCTIONS
  source $RM_STAGEDIR/00-LOCALENV
  env | grep RM_ | sort
else
  echo "     Can't find all my files:"
  ls -l $RM_STAGEDIR/00-FUNCTIONS
  ls -l $RM_STAGEDIR/00-LOCALENV
  exit 1
fi

if [[ ! -r "$RM_STAGEDIR/01_SRC_var_lib.tar" ||   \
      ! -r "$RM_STAGEDIR/01_SRC_etc_systemd_system.tar" ]]
then
  echo "     Have you run recover-machine-01-get-src-directories?"
  echo "     Can't find source archives in $RM_STAGEDIR"
  ls -l $RM_STAGEDIR/01_SRC_var_lib.tar
  ls -l $RM_STAGEDIR/01_SRC_etc_systemd_system.tar
  exit 1
else
  source $RM_STAGEDIR/00-FUNCTIONS
  source $RM_STAGEDIR/00-LOCALENV
fi

recover_mkdir $RM_STAGEDIR/03_TGT_NEW_var_lib
recover_mkdir $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system

echo "     Extract source directory archives into new target directories"
sudo tar -C $RM_STAGEDIR/03_TGT_NEW_var_lib            -x${V}f $RM_STAGEDIR/01_SRC_var_lib.tar
sudo tar -C $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system -x${V}f $RM_STAGEDIR/01_SRC_etc_systemd_system.tar
echo $RM_STAGEDIR/03_TGT_NEW_var_lib:
ls -l  $RM_STAGEDIR/03_TGT_NEW_var_lib
echo $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system:
ls -l  $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system

echo "     Edit new target files"
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/unit*
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/meter-status.yaml
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/locks/*
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/tools/unit*
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/metricspool
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/nonce.txt
sudo sh -c "echo $RM_TGT_MACHINE_NONCE > $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/nonce.txt"
sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RM_SRC_MACHINE} $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RM_TGT_MACHINE}
sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/tools/${RM_SRC_MACHINE}  $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/tools/${RM_TGT_MACHINE}
sudo sudo sed -i "s/${RM_SRC_MACHINE}/${RM_TGT_MACHINE}/g" $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RM_TGT_MACHINE}/agent.conf
sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_SRC_MACHINE}-exec-start.sh $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_TGT_MACHINE}-exec-start.sh
sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_SRC_MACHINE}.service       $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_TGT_MACHINE}.service
sudo sudo sed -i "s/${RM_SRC_MACHINE}/${RM_TGT_MACHINE}/g" $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_TGT_MACHINE}*

echo "     Diff of directories"
set +e # Temporarily don't exit on error because we expect diff to find differences
sudo diff --recursive --unified --no-dereference $RM_STAGEDIR/01_SRC_var_lib/juju/agents/${RM_SRC_MACHINE}/agent.conf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RM_TGT_MACHINE}/agent.conf
sudo diff --recursive --unified --no-dereference $RM_STAGEDIR/01_SRC_etc_systemd_system/jujud-*.sh      $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-*.sh
sudo diff --recursive --unified --no-dereference $RM_STAGEDIR/01_SRC_etc_systemd_system/jujud-*.service $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-*.service

echo "#### If any further edits or changes are needed, either add to this script and rerun or"
echo "#### manually edit/change $RM_STAGEDIR/03_TGT_NEW_* files as needed and proceed with next step."
