#!/usr/bin/bash

[[ -z "$DEBUG" ]] || set -x # Enable debugging
set -e # exit on error to be safe

if [[ -z "$RM_STAGEDIR" && -d _stage ]]
then
  export RM_STAGEDIR="_stage"
else
  echo "==== Did you run recover-machine-00-set-stage?"
  exit 1
fi

if [[ -r $RM_STAGEDIR/00-FUNCTIONS && \
        -r $RM_STAGEDIR/00-LOCALENV  ]]
then
  source $RM_STAGEDIR/00-FUNCTIONS
  source $RM_STAGEDIR/00-LOCALENV
else
  echo "==== Can't find all my files:"
  ls -l $RM_STAGEDIR/00-FUNCTIONS
  ls -l $RM_STAGEDIR/00-LOCALENV
  exit 1
fi

if [[ ! -r "$RM_STAGEDIR/01_SRC_var_lib.tar" ||   \
      ! -r "$RM_STAGEDIR/01_SRC_etc_systemd_system.tar" ]]
then
  echo -e "\n   Have you run recover-machine-01-get-src-directories?"
  echo -e "\n   Can't find source archives in $RM_STAGEDIR"
  ls -l $RM_STAGEDIR/01_SRC_var_lib.tar
  ls -l $RM_STAGEDIR/01_SRC_etc_systemd_system.tar
  exit 1
else
  source $RM_STAGEDIR/00-FUNCTIONS
  source $RM_STAGEDIR/00-LOCALENV
fi

recover_mkdir $RM_STAGEDIR/03_TGT_NEW_var_lib
recover_mkdir $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system

echo -e "\n   Extract source directory archives into target directories"
sudo tar -C $RM_STAGEDIR/03_TGT_NEW_var_lib            -x${V}f $RM_STAGEDIR/01_SRC_var_lib.tar
sudo tar -C $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system -x${V}f $RM_STAGEDIR/01_SRC_etc_systemd_system.tar
echo $RM_STAGEDIR/03_TGT_NEW_var_lib:
ls -l  $RM_STAGEDIR/03_TGT_NEW_var_lib
echo $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system:
ls -l  $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system

echo -e "\n   Edit target files"
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/unit*
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/meter-status.yaml
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/locks/*
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/tools/unit*
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/metricspool
sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/nonce.txt
sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RM_SRCMACHINE} $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RM_TGTMACHINE}
sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/tools/${RM_SRCMACHINE}  $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/tools/${RM_TGTMACHINE}
sudo sudo sed -i "s/${RM_SRCMACHINE}/${RM_TGTMACHINE}/g" $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RM_TGTMACHINE}/agent.conf
sudo diff --recursive --unified --no-dereference $RM_STAGEDIR/01_SRC_var_lib $RM_STAGEDIR/03_TGT_NEW_var_lib
sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_SRCMACHINE}-exec-start.sh $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_TGTMACHINE}-exec-start.sh
sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_SRCMACHINE}.service       $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_TGTMACHINE}.service
sudo sudo sed -i "s/${RM_SRCMACHINE}/${RM_TGTMACHINE}/g" $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_TGTMACHINE}*
sudo diff --recursive --unified --no-dereference $RM_STAGEDIR/01_SRC_var_lib $RM_STAGEDIR/03_TGT_NEW_var_lib

echo -e "\n    Archive target directories"
sudo tar -C $RM_STAGEDIR/03_TGT_NEW_var_lib            -c${V}f $RM_STAGEDIR/03_TGT_NEW_var_lib.tar            ./
sudo tar -C $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system -c${V}f $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system.tar ./
ls -l  $RM_STAGEDIR/03_TGT_NEW_var_lib.tar
ls -l  $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system.tar
