#!/usr/bin/bash

if [[ ! -d "$RECOVERY_STAGEDIR" ]]
then
  echo -e "\n    Did you run recover-machine-00-set-stage?"
  exit 1
elif [[ -r $RECOVERY_STAGEDIR/00-FUNCTIONS && \
        -r $RECOVERY_STAGEDIR/00-LOCALENV  ]]
then
  source $RECOVERY_STAGEDIR/00-FUNCTIONS 
  source $RECOVERY_STAGEDIR/00-LOCALENV 
else
  echo -e "\n    Can't find all my files:"
  ls -l $RECOVERY_STAGEDIR/00-FUNCTIONS
  ls -l $RECOVERY_STAGEDIR/00-LOCALENV
fi

echo -e "\n    Archive source directories on source machine"
juju ssh "$RECOVERY_SRC_MACHINENUM" sudo tar -C /var/lib -c${V}f /tmp/src_var_lib.tar \
                                            ./juju
juju ssh "$RECOVERY_SRC_MACHINENUM" sudo tar -C /etc/systemd/system -c${V}f /tmp/src_etc_systemd_system.tar \
                                            ./jujud-${RECOVERY_SRC_MACHINE}-exec-start.sh \
                                            ./jujud-${RECOVERY_SRC_MACHINE}.service
juju ssh "$RECOVERY_SRC_MACHINENUM" ls -l /tmp/src_*.tar

echo -e "\n    Retrieve source directory archives from source machine"
juju scp "$RECOVERY_SRC_MACHINENUM":/tmp/src_var_lib.tar            $RECOVERY_STAGEDIR/01_SRC_var_lib.tar
juju scp "$RECOVERY_SRC_MACHINENUM":/tmp/src_etc_systemd_system.tar $RECOVERY_STAGEDIR/01_SRC_etc_systemd_system.tar
ls -l $RECOVERY_STAGEDIR/01_SRC_*.tar

recover_mkdir $RECOVERY_STAGEDIR/01_SRC_var_lib
recover_mkdir $RECOVERY_STAGEDIR/01_SRC_etc_systemd_system

echo -e "\n    Extract source directories from archives"
sudo tar -C      $RECOVERY_STAGEDIR/01_SRC_var_lib            -x${V}f $RECOVERY_STAGEDIR/01_SRC_var_lib.tar
sudo tar -C      $RECOVERY_STAGEDIR/01_SRC_etc_systemd_system -x${V}f $RECOVERY_STAGEDIR/01_SRC_etc_systemd_system.tar
echo "$RECOVERY_STAGEDIR/01_SRC_var_lib:"
ls -l $RECOVERY_STAGEDIR/01_SRC_var_lib
echo "$RECOVERY_STAGEDIR/01_SRC_etc_systemd_system:"
ls -l $RECOVERY_STAGEDIR/01_SRC_etc_systemd_system
