#!/usr/bin/bash

[[ -z "$DEBUG" ]] || set -x # Enable debugging
set -e # exit on error to be safe

if [[ -z "$RM_STAGEDIR" && -d _stage ]]
then
  export RM_STAGEDIR="_stage"
else
  echo "==== Did you run recover-machine-00-set-stage?"
  exit 1
fi

if [[ -r $RM_STAGEDIR/00-FUNCTIONS && \
        -r $RM_STAGEDIR/00-LOCALENV  ]]
then
  source $RM_STAGEDIR/00-FUNCTIONS
  source $RM_STAGEDIR/00-LOCALENV
  env| grep RM_ | sort
else
  echo "==== Can't find all my files:"
  ls -l $RM_STAGEDIR/00-FUNCTIONS
  ls -l $RM_STAGEDIR/00-LOCALENV
  exit 1
fi

if [[ ! -d $RM_STAGEDIR/03_TGT_NEW_var_lib       || \
      ! -d $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system ]]
then
  echo "    Have you run recover-machine-03-edit-staged-tgt-target-directories?"
  echo "    Can't find target directories in $RM_STAGEDIR"
  ls -l $RM_STAGEDIR/03_TGT_NEW_var_lib
  ls -l $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system
  exit 1
fi
