#!/usr/bin/bash

[[ -z "$DEBUG" ]] || set -x # Enable debugging
set -e # exit on error to be safe

if [[ -z "$RM_STAGEDIR" && -d _stage ]]
then
  export RM_STAGEDIR="_stage"
else
  echo "==== Did you run recover-machine-00-set-stage?"
  exit 1
fi

if [[ -r $RM_STAGEDIR/00-FUNCTIONS && \
        -r $RM_STAGEDIR/00-LOCALENV  ]]
then
  source $RM_STAGEDIR/00-FUNCTIONS
  source $RM_STAGEDIR/00-LOCALENV
else
  echo "==== Can't find all my files:"
  ls -l $RM_STAGEDIR/00-FUNCTIONS
  ls -l $RM_STAGEDIR/00-LOCALENV
  exit 1
fi

echo -e "\n    Archive target directories on target machine"
juju ssh "$RM_TGT_MACHINE_NUM" sudo tar -C /var/lib -c${V}f /tmp/src_var_lib.tar \
                                                ./juju
juju ssh "$RM_TGT_MACHINE_NUM" sudo tar -C /etc/systemd/system -c${V}f /tmp/src_etc_systemd_system.tar \
                                                ./jujud-${RM_TGT_MACHINE}-exec-start.sh \
                                                ./jujud-${RM_TGT_MACHINE}.service
juju ssh "$RM_TGT_MACHINE_NUM" ls -l /tmp/src_*.tar

echo -e "\n    Retrieve target directory archives from target machine"
juju scp "$RM_TGT_MACHINE_NUM":/tmp/src_var_lib.tar            $RM_STAGEDIR/02_TGT_BKP_var_lib.tar
juju scp "$RM_TGT_MACHINE_NUM":/tmp/src_etc_systemd_system.tar $RM_STAGEDIR/02_TGT_BKP_etc_systemd_system.tar
ls -l $RM_STAGEDIR/02_TGT_BKP_*.tar

if [ -d $RM_STAGEDIR/02_TGT_BKP_var_lib ]
then
  timestamp=$(stat --format %y $RM_STAGEDIR/02_TGT_BKP_var_lib | tr ' :' '_-')
  echo -e "\n    Move old staged target backup directory $RM_STAGEDIR/02_TGT_BKP_var_lib out of the way to ${RM_STAGEDIR}/02_TGT_BKP_var_lib.${timestamp}"
  sudo mv $RM_STAGEDIR/02_TGT_BKP_var_lib  ${RM_STAGEDIR}/02_TGT_BKP_var_lib.${timestamp}
  ls -ld ${RM_STAGEDIR}/02_TGT_BKP_var_lib.${timestamp}
fi

if [ -d $RM_STAGEDIR/02_TGT_BKP_etc_systemd_system ]
then
  timestamp=$(stat --format %y $RM_STAGEDIR/02_TGT_BKP_etc_systemd_system | tr ' :' '_-')
  echo -e "\n    Move old staged backup target directory $RM_STAGEDIR/02_TGT_BKP_etc_systemd_system out of the way to ${RM_STAGEDIR}/02_TGT_BKP_etc_systemd_system.${timestamp}"
  sudo mv $RM_STAGEDIR/02_TGT_BKP_etc_systemd_system $RM_STAGEDIR/02_TGT_BKP_etc_systemd_system.${timestamp}
  ls -ld  $RM_STAGEDIR/02_TGT_BKP_etc_systemd_system.${timestamp}
fi

recover_mkdir $RM_STAGEDIR/02_TGT_BKP_var_lib
recover_mkdir $RM_STAGEDIR/02_TGT_BKP_etc_systemd_system

echo -e "\n    Extract target directories from archives"
sudo tar -C      $RM_STAGEDIR/02_TGT_BKP_var_lib            -x${V}f $RM_STAGEDIR/02_TGT_BKP_var_lib.tar
sudo tar -C      $RM_STAGEDIR/02_TGT_BKP_etc_systemd_system -x${V}f $RM_STAGEDIR/02_TGT_BKP_etc_systemd_system.tar
echo "$RM_STAGEDIR/02_TGT_BKP_var_lib:"
ls -l $RM_STAGEDIR/02_TGT_BKP_var_lib
echo "$RM_STAGEDIR/02_TGT_BKP_etc_systemd_system:"
ls -l $RM_STAGEDIR/02_TGT_BKP_etc_systemd_system
