#!/usr/bin/bash

[[ -z "$DEBUG" ]] || set -x # Enable debugging
set -e # exit on error to be safe

if [[ -z "$RM_STAGEDIR" && -d _stage ]]
then
  export RM_STAGEDIR="_stage"
else
  echo "     Did you run recover-machine-00-set-stage?"
  exit 1
fi

if [[ -r $RM_STAGEDIR/00-FUNCTIONS && \
        -r $RM_STAGEDIR/00-LOCALENV  ]]
then
  source $RM_STAGEDIR/00-FUNCTIONS
  source $RM_STAGEDIR/00-LOCALENV
  env| grep RM_ | sort
else
  echo "     Can't find all my files:"
  ls -l $RM_STAGEDIR/00-FUNCTIONS
  ls -l $RM_STAGEDIR/00-LOCALENV
  exit 1
fi

if [[ ! -r $RM_STAGEDIR/04_TGT_NEW_var_lib.tar       || \
      ! -r $RM_STAGEDIR/04_TGT_NEW_etc_systemd_system.tar ]]
then
  echo "===> Have you run recover-machine-04-archive-and-upload-new-target-directories"
  echo "===> Can't find target directories in $RM_STAGEDIR"
  ls -l $RM_STAGEDIR/04_TGT_NEW_var_lib.tar
  ls -l $RM_STAGEDIR/04_TGT_NEW_etc_systemd_system.tar
  exit 1
fi

echo "     Stop and disable juju systemd units on target machine"
juju ssh $RM_INSTALLING_UNIT "sudo systemctl stop    jujud-${RM_INSTALLING_UNIT_FILENAME}.service"
juju ssh $RM_INSTALLING_UNIT "sudo systemctl disable jujud-${RM_INSTALLING_UNIT_FILENAME}.service"
juju ssh $RM_INSTALLING_UNIT 'sudo systemctl daemon-reload'

echo "     Extract archived directories"
juju ssh $RM_INSTALLING_UNIT 'sudo tar -xvf /tmp/04_TGT_NEW_var_lib.tar            -C /var/lib            --skip-old-files --keep-directory-symlink --dereference'
juju ssh $RM_INSTALLING_UNIT 'sudo tar -xvf /tmp/04_TGT_NEW_etc_systemd_system.tar -C /etc/systemd/system --skip-old-files --keep-directory-symlink --dereference'

echo "     Update unit password"
cat <<END > $RM_STAGEDIR/00-MONGO_CODE
use juju
db.units.update({"_id": "${RM_MODEL_UUID}:${RM_INSTALLING_UNIT}"}, {\$set:{"passwordhash": "$RM_ACTIVE_UNIT_PWHASH"}})
END
juju scp -m controller $RM_STAGEDIR/00-MONGO_CODE "$RM_CTRLR_NUM":/tmp/
juju ssh -m controller ubuntu@$RM_CTRLR_NUM sudo bash /tmp/00-MONGO_RUN-CODE | tr -d '\r'

echo "     Enable and start juju systemd units on target machine"
juju ssh $RM_INSTALLING_UNIT 'sudo systemctl daemon-reload'
juju ssh $RM_INSTALLING_UNIT "sudo systemctl enable  jujud-${RM_INSTALLING_UNIT_FILENAME}.service"
juju ssh $RM_INSTALLING_UNIT "sudo systemctl start   jujud-${RM_INSTALLING_UNIT_FILENAME}.service"

